from flask import Flask, render_template, request, redirect, session
import random
app = Flask(__name__)
app.secret_key = "UcEsM9TWsF.!CbnK2w*s" #generated by password gen



@app.route('/')
@app.route('/<int:plus>')
def index(plus = 1):
    session['color'] = 'red'
    session['guesses'] = 0
    session['guess'] = 0 # beloww all possible values
    r = 'rand'
    if r not in session:
        num = random.randint(1,100)
        session[r] = num

    return render_template("index.html",
    num=session[r], guesses=session['guesses'], color=session['color'])

@app.route('/guess', methods=['POST'])
def guess():
    if request.form['guess'] == session[r]:
        return redirect('/correct')
    session['guesses'] += 1
    session['userVal'] = int(request.form['custNum'])
    return redirect('/')

@app.route('/correct')
def correct():
    session['color'] = 'green'
    return redirect('/')

@app.route('/reset')
def reset():
    session.clear()
    return redirect('/')


@app.errorhandler(404)
def fourZeroFour(err):
    return "Sorry! No response. Try again."

if __name__ == "__main__":
    app.run(debug=True)