num1 = 42 # variable declaration, number (int)
num2 = 2.3 # variable declaration, number (float)
boolean = True # variable declaration, boolean
string = 'Hello World' # variable declaration, string
pizza_toppings = ['Pepperoni', 'Sausage', 'Jalepenos', 'Cheese', 'Olives'] # variable declaration, list
person = {'name': 'John', 'location': 'Salt Lake', 'age': 37, 'is_balding': False} # variable declaration, dictionary
fruit = ('blueberry', 'strawberry', 'banana') # variable declaration, tuple
print(type(fruit)) # log statement, type check
print(pizza_toppings[1]) # log statement, list access value
pizza_toppings.append('Mushrooms') # list add value
print(person['name']) # log statement, dictionary access value
person['name'] = 'George' # dictionary change value
person['eye_color'] = 'blue' # dictionary add/change value
print(fruit[2]) # log statement, list access value

if num1 > 45: # conditional if
    print("It's greater") # log string
else: # else
    print("It's lower") # log string

if len(string) < 5: # if string length
    print("It's a short word!") #log string
elif len(string) > 15: #else if string length
    print("It's a long word!") #log string
else: # else
    print("Just right!") # log string

for x in range(5): # for loop start, sequence generated by range with stop
    print(x) # log variable
for x in range(2,5): # for loop start, sequence generated by range with start/stop
    print(x) # log variagble
for x in range(2,10,3): # for loop start, sequence generated by range with start/stop/increment
    print(x) # log variable
x = 0 # variable declaration, number (int)
while(x < 5): # while loop start
    print(x) # log variable
    x += 1 # increment by 1

pizza_toppings.pop() # list delete last element
pizza_toppings.pop(1) # list delete element at index 1

print(person) # log dictionary
person.pop('eye_color') # dictionary delete value
print(person) # log dictionary

for topping in pizza_toppings: # for loop list sequence
    if topping == 'Pepperoni': # if conditional
        continue # for loop continue
    print('After 1st if statement') # log string
    if topping == 'Olives': # if conditional
        break # for loop break

def print_hello_ten_times(): # function defition
    for num in range(10): # for loop, sequence generated by range
        print('Hello') # log statement

print_hello_ten_times() # function call

def print_hello_x_times(x): # function defintion with parameter
    for num in range(x): # for loop, sequence generated by range
        print('Hello') # log statement

print_hello_x_times(4) # function call with argument

def print_hello_x_or_ten_times(x = 10): # function defition, parameter with default value
    for num in range(x): # for loop, sequence generated by range
        print('Hello') # log statement

print_hello_x_or_ten_times() # function call, no argument - default gets used
print_hello_x_or_ten_times(4) # function call with argument

# multiline comment
"""
Bonus section
"""

# print(num3) ## NameError (num 3 never declared/defined)
# num3 = 72 ## variable declaration, num
# fruit[0] = 'cranberry' ## TypeError: 'tuple' object does not support item assignment
# print(person['favorite_team']) ## - KeyError: 'favorite_team'
# print(pizza_toppings[7]) ## list index out of range
#   print(boolean) ## IndentationError: unexpected indent
# fruit.append('raspberry') ## AttributeError: 'tuple' object has no attribute 'append'
# fruit.pop(1) ## AttributeError: 'tuple' object has no attribute 'pop'
