from flask import Flask, render_template, request, redirect, session

app = Flask(__name__)
app.secret_key = "@-*._2*cEAPii*_eKkNc" #generated by password gen

debug = True

@app.route('/')
def index():
    
    return render_template("index.html")

@app.route('/process', methods=['POST'])
def process():
    if debug:
        print(request.form)
    return redirect('/result')

@app.route('/result')
def result():

    return redirect('/')

@app.errorhandler(404)
def fourZeroFour(err):
    return "Sorry! No response. Try again."

if __name__ == "__main__":
    app.run(debug=True)