from flask import Flask, render_template, request, redirect, session

app = Flask(__name__)
app.secret_key = "UcEsM9TWsF.!CbnK2w*s" #generated by password gen


@app.route('/')
@app.route('/<int:plus>')
def index(plus = 1):
    c = 'counter'
    if c in session:
        session[c] += plus
    else:
        session[c] = plus
    return render_template("index.html", counter=session[c])

@app.route('/destroy_session')
def create_user():
    session.clear() # it's called destroy session, not reset session key!
    return redirect('/')

if __name__ == "__main__":
    app.run(debug=True)
