from flask import Flask, render_template, request, redirect, session

app = Flask(__name__)
app.secret_key = "UcEsM9TWsF.!CbnK2w*s" #generated by password gen


@app.route('/')
@app.route('/count')
def index():
    c = 'counter'
    if c in session:
        session[c] += 1
    else:
        session[c] = 1
    return render_template("index.html", counter=session[c])

@app.route('/destroy_session')
def create_user():
    session.clear() # it's called destroy session, not reset session key!
    return redirect('/')

@app.route('/doubledown')
def doubledown():
    session['counter'] += 1
    return redirect('/')

if __name__ == "__main__":
    app.run(debug=True)
